# Copyright (C) 2026: OpenCL FDTD Solver Contributors
# Derived from gprMax (Copyright (C) 2015-2023: The University of Edinburgh)
#
# This file is part of opencl-fdtd-solver.

"""Objective OpenCL ↔ Meep near-to-far pattern discrepancy metrics."""

from __future__ import annotations

import json
from pathlib import Path
from typing import Any

import numpy as np

from .harness import max_abs_db_error


def _round_metric(x: float) -> float:
    return float(f"{float(x):.8g}")


def null_ratio(eh_main: np.ndarray, eh_null: np.ndarray) -> float:
    """|E(null)| / |E(main)| from packed 6-vectors."""
    a = np.asarray(eh_main, dtype=np.complex128)
    b = np.asarray(eh_null, dtype=np.complex128)
    return float(np.linalg.norm(b[:3]) / (np.linalg.norm(a[:3]) + 1e-30))


def measure_farfield_case(
    ocl_db: np.ndarray,
    meep_db: np.ndarray,
    ocl: dict[str, Any],
    meep: dict[str, Any],
    *,
    mask_db: float = -12.0,
) -> dict[str, float]:
    """Pattern + null-depth metrics for one far-field case."""
    err = max_abs_db_error(
        np.asarray(ocl_db, dtype=np.float64),
        np.asarray(meep_db, dtype=np.float64),
        mask_db=mask_db,
    )
    return {
        "main_lobe_max_abs_db_error": _round_metric(err),
        "opencl_null_ratio": _round_metric(
            null_ratio(ocl["eh_plus_z"], ocl["eh_plus_x"])
        ),
        "meep_null_ratio": _round_metric(
            null_ratio(meep["eh_plus_z"], meep["eh_plus_x"])
        ),
    }


def build_farfield_discrepancy_document(cases: list[dict[str, Any]]) -> dict[str, Any]:
    return {
        "title": "OpenCL ↔ Meep near-to-far discrepancy report",
        "description": (
            "Objective comparison of XZ far-field |S|(θ) and null depth between "
            "OpenCLNear2FarMonitor and Meep Near2Far on shared compact-patch cases."
        ),
        "metric_definitions": {
            "main_lobe_max_abs_db_error": (
                "Max |Δ| after aligning each pattern's peak to 0 dB, restricted to "
                "angles within mask_db=-12 of both peaks."
            ),
            "opencl_null_ratio": "|E(+x)| / |E(+z)| on OpenCL (Ex-dipole endfire null).",
            "meep_null_ratio": "|E(+x)| / |E(+z)| on Meep (H scaled to SI).",
        },
        "cases": cases,
    }


def discrepancy_farfield_markdown(doc: dict[str, Any]) -> str:
    lines = [
        f"# {doc['title']}",
        "",
        doc["description"],
        "",
        "## Metric definitions",
        "",
    ]
    for key, text in doc["metric_definitions"].items():
        lines.append(f"- **`{key}`:** {text}")
    lines.append("")

    for case in doc["cases"]:
        lines.extend(
            [
                f"## Case `{case['name']}`",
                "",
                (
                    f"- Grid `{tuple(case['shape'])}`, dl={case['dl_m']} m, "
                    f"npml={case['npml']}, n_steps={case['n_steps']}, "
                    f"n_angles={case['n_angles']}"
                ),
                (
                    f"- Source freq={case['freq_hz']} Hz, fwidth={case['fwidth_hz']} Hz; "
                    f"Courant={case['courant']}"
                ),
                (
                    f"- Sphere ε={case['sphere_eps']}, rad_cells={case['sphere_rad_cells']}; "
                    f"main-lobe gate < {case['max_main_lobe_db']} dB"
                ),
                "",
                "### Summary",
                "",
                "| main lobe |Δ|dB | OpenCL null | Meep null |",
                "|-------------------:|------------:|----------:|",
            ]
        )
        m = case["metrics"]
        lines.append(
            f"| {m['main_lobe_max_abs_db_error']:.6f} | "
            f"{m['opencl_null_ratio']:.6e} | {m['meep_null_ratio']:.6e} |"
        )
        lines.append("")
        if case.get("images"):
            lines.append("### Images")
            lines.append("")
            for img in case["images"]:
                lines.append(f"- [`{img}`]({case['name']}/{img})")
            lines.append("")
    lines.append(
        "_Generated by `python -m tests.meep_validation.update_farfield_baselines`. "
        "CI requires this file and `discrepancy_report_farfield.json` to match a fresh run._"
    )
    lines.append("")
    return "\n".join(lines)


def write_farfield_discrepancy_reports(
    root: Path, doc: dict[str, Any]
) -> tuple[Path, Path]:
    root = Path(root)
    root.mkdir(parents=True, exist_ok=True)
    json_path = root / "discrepancy_report_farfield.json"
    md_path = root / "DISCREPANCY_REPORT_FARFIELD.md"
    json_path.write_text(json.dumps(doc, indent=2, sort_keys=True) + "\n", encoding="utf-8")
    md_path.write_text(discrepancy_farfield_markdown(doc), encoding="utf-8")
    return json_path, md_path


def case_farfield_report_dict(
    *,
    name: str,
    shape: list[int],
    dl_m: float,
    npml: int,
    n_steps: int,
    freq_hz: float,
    fwidth_hz: float,
    n_angles: int,
    sphere_eps: float | None,
    sphere_rad_cells: int,
    max_main_lobe_db: float,
    courant: float,
    metrics: dict[str, float],
    images: list[str],
) -> dict[str, Any]:
    return {
        "name": name,
        "shape": list(shape),
        "dl_m": dl_m,
        "npml": npml,
        "n_steps": n_steps,
        "freq_hz": freq_hz,
        "fwidth_hz": fwidth_hz,
        "n_angles": n_angles,
        "sphere_eps": sphere_eps,
        "sphere_rad_cells": sphere_rad_cells,
        "max_main_lobe_db": max_main_lobe_db,
        "courant": courant,
        "metrics": metrics,
        "images": list(images),
    }
